theme = "spf13"
baseurl = "http://Cognitio.net/"
languageCode = "fr-fr"
title = "Cognitio.net"
MetaDataFormat = "yaml"
author = "Sébastien Boisard"
# Shown in the side menu
copyright = "&copy; 2002 - 2016, Sébastien Boisard; all rights reserved."
canonifyurls = true
paginate = 10
disqusShortname = "cognitio-net"
googleAnalytics = "Your Google Analytics tracking ID"


[indexes]
  tag = "tags"
  topic = "topics"

